<?php

namespace backend\modules\settings\controllers;

use backend\controllers\CRUDController;
use backend\models\SocialLink;
use backend\models\search\SocialLinkSearch;

/**
 * SocialLinksController implements the CRUD actions for SocialLink model.
 */
class SocialLinksController extends CRUDController
{

    /**
     * Init bean class
     */
    public function init()
    {
        $this->beanClass = SocialLink::className();
        $this->beanSearchClass = SocialLinkSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

}
