<?php

namespace backend\modules\settings\controllers;

use backend\controllers\CRUDController;
use backend\models\Stock;
use backend\models\search\StockSearch;

/**
 * StocksController implements the CRUD actions for Stock model.
 */
class StocksController extends CRUDController
{

    /**
     * Init bean class
     */
    public function init()
    {
        $this->beanClass = Stock::className();
        $this->beanSearchClass = StockSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

}
